# Generated by Django 4.0.4 on 2022-05-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_rename_user_id_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.CharField(max_length=150),
        ),
    ]
